### ISSUE TITLE
Zero abundances is chemical composition. 

### ISSUE THREAD

**Issue by Andrey890** [hombit/mesa2py#5]
Wrong processing of zero abundances, when setting up the chemical composition:

``` python3
from opacity import Opac
op = Opac({'h1': 1.0, 'he4': 0.0})
```
returns
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "opacity.pyx", line 247, in opacity.Opac.__new__
  File "opacity.pyx", line 243, in genexpr
  File "opacity.pyx", line 243, in genexpr
  File "opacity.pyx", line 241, in genexpr
  File "opacity.pyx", line 216, in opacity.signif
ValueError: math domain error
```

The error is in [opacity.pyx](https://github.com/hombit/mesa2py/blob/93151bd6edbac5678b95cfbd8ce701081136df1e/opacity.pyx#L216) in `signif` function (calculation of log10(0)). 
The solution is to change two lines:
```python3
def signif(x, p):
    """Inspired by https://stackoverflow.com/a/59888924/5437597"""
    x_positive = np.where(x != 0, np.abs(x), 10**p)  # new line
#    mags = 10 ** (p - m.floor(m.log10(x)))
    mags = 10 ** (p - m.floor(m.log10(x_positive)))  # change line
    return round(x * mags) / mags
```
Also why do you use `math` instead of `numpy`? `math` is used only here in two places.

**Comment by hombit** [comment]
Why do we need np.abs?

**Comment by Andrey890** [comment]
I realised, that we check whether composition values are non-negative before the signif call. So we don't need np.abs. We can additionally check composition for infty and NaN before the normalisation calculation.
